### ISSUE TITLE
Issue scanning QR codes with front camera

### ISSUE THREAD

**Issue by AmilaDiman** [mikebuss/MTBBarcodeScanner#88] opened 2016-10-21 09:34 UTC
Because the front cameras automatically flip the image, the library does not seem to detect the QR code. Is there a separate setting that I should enable when using the front camera or do I have to handle that?

**Comment by mikebuss** [comment] 2016-10-23 03:56
Hi @AmilaDiman. I am able to scan QR codes using the front-facing camera of both an iPhone 7 Plus and an iPad Air 2. The code I'm scanning it from the search page [here](https://www.google.com/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=qr%20code&oq=qr%20code&aqs=chrome.0.0l6.1136j0j7).

What devices are you using to scan the code? Is it possible the QR code is blurry or invalid? If the device you're using is fairly old, the front-facing camera may not be high enough quality to scan the code.

I am going to close this issue since it doesn't seem to be a problem with MTBBarcodeScanner specifically, but please comment here if you have further updates.

**Closed by mikebuss** 2016-10-23 03:56 UTC

**Comment by AmilaDiman** [comment] 2016-10-25 03:37
Hi @mikebuss, I tried it with an iPad Mini 4 and an iPad 2. The scanning from front camera only works if I manually flip the QR code horizontally. There is no special setting I have to set right?

**Comment by AmilaDiman** [comment] 2016-10-25 04:16
Hey @mikebuss , I found the issue. When using [self.scanner flipCamera] method, it does not work. When using self.scanner.camera = MTBCameraFront, it works!

**Comment by thibauddavid** [comment] 2017-03-02 15:48
Hi, same behavior for me (iPhone 6s), except setting camera to MTBCameraFront doesn't help.
Any idea ?

**Comment by mikebuss** [comment] 2017-03-02 17:11
@thibauddavid can you share what version of MTBBarcodeScanner you're using? Also, as much of the code as you can share would be helpful.

**Comment by thibauddavid** [comment] 2017-03-02 17:17
I'm using last version I guess, as my pod is `pod 'MTBBarcodeScanner'`

My code is pretty straightforward:

viewDidLoad:
`self.scanner = [[MTBBarcodeScanner alloc] initWithPreviewView:self.previewView];`

viewDidAppear:
```
[MTBBarcodeScanner requestCameraPermissionWithSuccess:^(BOOL success) {
        if (success) {
            [weakSelf.scanner startScanningWithResultBlock:^(NSArray *codes)
            { /* here, calling stopping scanner and delegating event */ }
        } else { /* Handling error */ }
}
```

And then, I have de double-tap gesture which calls `flipCamera` on scanner.
I've tried to switch camera manually too by using `self.scanner.camera = self.scanner.camera == MTBCameraFront ? MTBCameraBack : MTBCameraFront;`

By the way, front camera doesn't seem to adjust focus. Could be related ?

**Comment by mikebuss** [comment] 2017-03-02 17:57
To make sure you're on the latest version, can you update your Podfile to:

```ruby
pod 'MTBBarcodeScanner', '5.0.0'
```

And then run another `pod install`?

The latest version of the code makes the `camera` property readonly, and based on your example it might mean you're on an older version.

If you can, can you also try in the sample project in this repository and see if that has the same issue for you? I was able to scan codes using both the front and back camera using the example on an iPhone 7 Plus. There is a little white icon in the top-right of the preview that lets you flip cameras during capture.

Let me know if this helps!

**Comment by thibauddavid** [comment] 2017-03-02 19:24
Wait... 5.0.0 ?
My pod install results in `Using MTBBarcodeScanner (1.9.1)`, and found why : 5.0.0 requires targeting iOS >8
Guess it's time to upgrade my min deployment target :)

Unfortunately, upgrading did not change anything. I then tried your sample project... And still doesn't work.

Sure mirrored effect from front camera doesn't affect ean13 detection ?

**Comment by mikebuss** [comment] 2017-03-02 19:31
Ok, I was able to reproduce this on my end. For whatever reason, I can scan QR codes using the front camera, but the few EIN13 codes I tried from a Google search could _only_ scan on the back camera...

I think this may be a problem with AVFoundation since the front camera resolution should be fine for this, but I'll dig a big further to see what's going on. If it turns out to be a bug in AVFoundation, I'll file a radar to Apple and link it here.

Thanks for bringing this to my attention!

**Comment by thibauddavid** [comment] 2017-03-02 19:32
Great you were able to reproduce it, and thanks for digging in !
If you remember, I'd love to get news about this  :)

**Comment by mikebuss** [comment] 2017-03-02 19:45
Can you try scanning this EIN13 code? You may need to hit CMD and + a bunch of times to make it larger, but it is a SVN so it can get as large as you need:
https://upload.wikimedia.org/wikipedia/commons/a/a2/EAN-13-5901234123457.svg

I believe the issue here is due to the front camera being much lower resolution than the back camera, which makes it harder for these codes to be detected. I was able to scan the above code using the front camera, but only after I resized it to be extremely large.

**Comment by thibauddavid** [comment] 2017-03-02 19:47
Right, scanning works by using that one zoomed. But iPhone 6s front camera resolution is way better than back camera of previous devices, and yet my iPhone 4 can scan without any problem :/
