### ISSUE TITLE
could not scan in ios 10.2 and xcode 8.2 on ipad

### ISSUE THREAD

**Issue by iosmiracle** [mikebuss/MTBBarcodeScanner#99] opened 2017-01-17 11:25 UTC
could not scan in ios 10.2 and xcode 8.2 on ipad. Its working fine on iphone but not able to scan on ipad

**Comment by mikebuss** [comment] 2017-01-17 14:37
This library is being used in production apps running on iPad 10.2. Can you share the code you are trying to scan? What model of iPad are you using?

**Comment by mikebuss** [comment] 2017-01-17 18:41
I'm going to close this for now as I can't reproduce it but please add further details if you have them,

**Closed by mikebuss** 2017-01-17 18:41 UTC

**Comment by sw-tt-krutikvora** [comment] 2017-02-21 13:37
Hello,

I am facing issue like barcode scanner camera is open successfully but barcode can not able to scanned. To resolve this issue. i have to go for setting-> My Application -> Off/On camera permission and come back to my app. then my barcode successfully scan.
i am using iPad Air with iOS 10.1. ( Already allow camera permission when application start)
I have not always facing this issue.

Let me know how to resolve this issue.

Thanks,
Krutik

**Comment by mikebuss** [comment] 2017-02-22 02:41
@sw-tt-krutikvora If you haven't already, can you try running the demo application included with this repo on your iPad? If you are able to reproduce the issue with this project, I can take a look on my end.
